databases:
  - name: blog-app
    databaseName: blog-app
    user: blog-app

services:
  - type: web
    name: blog-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false